
###수강 신청
POST http://localhost:2000/api/v1/application
Content-Type: application/json
member-id: 08514078-3d35-41ce-90ee-d4954c5764e9

{
  "lectureId": 1003,
  "lectureName": "실용 음악1",
  "professorName": "교수1",
  "maximumNumber": 10,
  "weekday": "TURSDAY",
  "score": 4,
  "semester": "FIRST",
  "startTime": 1
}



###수강 취소
DELETE http://localhost:2000/api/v1/application
Content-Type: application/json

{
  "lectureId" : 1004,
  "memberId" : "08514078-3d35-41ce-90ee-d4954c5764e9"
}

###수강 허가
POST http://localhost:2000/api/v1/manager/application/accepted
Content-Type: application/json

{
  "applicationId": 2,
  "lectureId": 1003,
  "memberId": "08514078-3d35-41ce-90ee-d4954c5764e9"
}

